<a href="https://colab.research.google.com/github/mary270/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY EXERCISE


1. Import the numpy package under the name np

In [ ]:
import numpy 

In [ ]:
arr = numpy.array([1,5,7,9,0]) #1-D array
arr1 = numpy.array([[3,7,8],[0,6,4]])
print(arr1)
print(arr)

[[3 7 8]
 [0 6 4]]
[1 5 7 9 0]


2. Print the numpy version and the configuration 

In [ ]:
import numpy as np

print(np.__version__) #numpy version

1.22.4


3. Create a null vector of size 10

In [ ]:
arr2 = numpy.zeros(10)  # using zeros
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 4- How to find the memory size of any array

In [ ]:
arr = numpy.zeros((5,5))
print("%d bytes " % (arr.size * arr.itemsize))

200 bytes 


5. How to get the documentation of the numpy add function from the command line?


In [ ]:
arr = numpy.array((4,4))
arr
a= (np.info())
print(a)


ERROR:root:File `'python.py'` not found.


 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f863248b7f0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

In [ ]:
%run python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'python.py'` not found.


6. Create a null vector of size 10 but the fifth value which is 1


In [ ]:
arr = numpy.zeros((10,10))
arr[4] =1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


7. Create a vector with values ranging from 10 to 49

In [ ]:
arr = np.arange(10,50)  # using np.arange
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [ ]:
arr = numpy.array((10,4,8,7,4))
v=arr[::-1]
print(v)

[ 4  7  8  4 10]


In [ ]:
arr = np.arange(50)
v=arr[::-1]
print(arr)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
arr = np.nonzero([1,2,0,0,4,0])

print(arr)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix 

In [ ]:
arr = np.eye(3) # np.eye will create 3 by 3 identity matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [ ]:
arr = np.random.random((3,3,3))
arr

array([[[0.32640056, 0.50369369, 0.05749176],
        [0.12038675, 0.69962322, 0.03921857],
        [0.38571985, 0.58177093, 0.69597334]],

       [[0.75728932, 0.08393615, 0.3532424 ],
        [0.75773732, 0.95577354, 0.97136382],
        [0.03918007, 0.37803187, 0.94842436]],

       [[0.32613536, 0.99848398, 0.94307428],
        [0.06084309, 0.34807776, 0.25368492],
        [0.69045245, 0.18910755, 0.57842393]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr = np.random.random((10,10))
min = arr.min()
print(arr)
print(min)
max= arr.max()
print(max)

[[0.71949624 0.05221271 0.10892797 0.15452723 0.25529758 0.16287985
  0.74092651 0.68589726 0.01844658 0.04499879]
 [0.0818968  0.22764811 0.84272431 0.84484981 0.63540361 0.00394803
  0.57552776 0.01577282 0.23476525 0.8036728 ]
 [0.86546483 0.57390165 0.14248913 0.93140697 0.41856572 0.04238974
  0.54143086 0.57815878 0.92391207 0.45409354]
 [0.94815394 0.0825381  0.49048139 0.20029617 0.85777418 0.05862992
  0.77144813 0.45226589 0.39109515 0.72161995]
 [0.92146961 0.06972712 0.79486934 0.24323586 0.99380539 0.6372932
  0.44667217 0.70851775 0.90378339 0.61790817]
 [0.59743606 0.69226468 0.93841661 0.21150827 0.86397083 0.00366422
  0.37990339 0.94116789 0.12569509 0.78566346]
 [0.27692195 0.18195966 0.0511415  0.36334764 0.05596746 0.14603014
  0.97670106 0.44267498 0.5549207  0.83144873]
 [0.01484155 0.69661461 0.55647164 0.24012884 0.30632456 0.82692691
  0.4623454  0.69545377 0.9420381  0.71754045]
 [0.16401659 0.11887325 0.6368174  0.61585577 0.94952987 0.30652587
  0.14810918 

14. Create a random vector of size 30 and find the mean value

In [ ]:
arr = np.random.random(30)
print(arr)
mean = arr.mean()
print(mean)

[0.27500547 0.83286255 0.37717887 0.82408722 0.03940758 0.40696203
 0.17707378 0.33422678 0.32002004 0.29621847 0.94826565 0.06703005
 0.23526715 0.29003586 0.70726207 0.07201682 0.17935489 0.18674021
 0.6423102  0.16518109 0.84737217 0.06154231 0.37429617 0.71334324
 0.9044616  0.63648382 0.20773091 0.05326754 0.51934374 0.1560737 ]
0.3950140662763219


15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? 

In [ ]:
arr = np.ones((7,7))
arr[:,[0,1]]=0
arr[[0,1],:]=0
print(arr)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]]


In [ ]:
arr = np.ones((3,3))
np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(type(arr))

<class 'numpy.ndarray'>


17. What is the result of the following expression?

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
arr = np.diag(1+np.arange(4), k= -1)
print (arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [ ]:
arr = np.unravel_index(99,(6,7,8))
print(arr)

(1, 5, 3)
